module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",
    UPDATE_USER_EMAIL: "UPDATE_USER_EMAIL",

    ADD_NEW_TESTIMONY: "ADD_NEW_TESTIMONY",
    UPDATE_TESTIMONY: "UPDATE_TESTIMONY",

    ADD_NEW_PARTNER: "ADD_NEW_PARTNER",
    UPDATE_PARTNER: "UPDATE_PARTNER",

    ADD_NEW_EVENT: "ADD_NEW_EVENT",
    UPDATE_EVENT: "UPDATE_EVENT",

    ADD_NEW_NEWS: "ADD_NEW_NEWS",
    UPDATE_NEWS: "UPDATE_NEWS",

    ADD_NEW_ARTICLE: "ADD_NEW_ARTICLE",
    UPDATE_ARTICLE: "UPDATE_ARTICLE",

    ADD_NEW_HOSTCENTER: "ADD_NEW_HOSTCENTER",
    UPDATE_HOST_CENTER: "UPDATE_HOST_CENTER",

    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    PARTNER_DELETE: "PARTNER_DELETE",
    TESTIMONY_DELETE: "TESTIMONY_DELETE",
    EVENT_DELETE: "EVENT_DELETE",
    NEWS_DELETE: "NEWS_DELETE",
    ARTICLE_DELETE: "ARTICLE_DELETE",
    TEAM_DELETE: "TEAM_DELETE",
    HOSTCENTER_DELETE: "HOSTCENTER_DELETE",
    PROGRAM_DELETE: "PROGRAM_DELETE",
  },
  SHOW_MODAL_TYPES: {
    SHOW_NEW_EVENT: "SHOW_NEW_EVENT",
  },
});
